### ISSUE TITLE
Invalid License

### ISSUE THREAD

**Issue by PepperCode1** [Cy4Shot/ItemStitchingFix#1]
I noticed that the repository is missing a license, meaning it is All Rights Reserved. The original mod's source code is licensed under LGPL-3.0, meaning that any derivative works must also be licensed under LGPL-3.0. Additionally, the CurseForge page's license is MIT and this is also invalid since all *GPL licenses require the compiled software to be licensed the same as the source.

**Comment by Cy4Shot** [comment]
Apologies, it has now been fixed!

**Comment by triphora** [comment]
@Cy4Shot The license is still invalid. You have selected the *GPL-3.0*, but the original mod is *LGPL-3.0*. Additionally, even if you were given the go-ahead to use the GPL, the GPL cannot be used for Minecraft because it is a proprietary application, and the GPL does not allow linking in that fashion (more information on that [here](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins)). Please change the license to have the [LGPL-3.0](https://www.gnu.org/licenses/lgpl-3.0.txt) appropriately.
